services:
  bot:
    build: .
    container_name: ${APP_NAME:-hono-bot-wa}
    ports:
      - "${PORT:-1997}:${PORT:-1997}"
    env_file:
      - .env
    volumes:
      - /opt/wa-auth:/app/.wwebjs_auth
      - /opt/wa-cache:/app/.wwebjs_cache
    restart: unless-stopped 
    command: bun run start
